/**
 * Sentinel — Multi-format report generation.
 * Produces professional pentest reports in Markdown, SARIF 2.1.0, JSON, and CSV
 * from a completed or in-progress ScanJob.
 */

import type { Finding, ScanJob, SeverityLevel } from "./types.js";

// ─────────────────────────────────────────────────────────────────────────────
// Shared helpers
// ─────────────────────────────────────────────────────────────────────────────

const SEVERITY_ORDER: SeverityLevel[] = [
	"critical",
	"high",
	"medium",
	"low",
	"info",
];

function capitalise(s: string): string {
	return s.charAt(0).toUpperCase() + s.slice(1);
}

function severityCounts(findings: Finding[]): Record<SeverityLevel, number> {
	const counts: Record<SeverityLevel, number> = {
		critical: 0,
		high: 0,
		medium: 0,
		low: 0,
		info: 0,
	};
	for (const f of findings) {
		counts[f.severity] = (counts[f.severity] ?? 0) + 1;
	}
	return counts;
}

function activeFindings(job: ScanJob): Finding[] {
	return job.findings.filter((f) => !f.falsePositive);
}

// ─────────────────────────────────────────────────────────────────────────────
// Markdown report
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generates a professional penetration-test-style Markdown report with:
 * executive summary, risk heatmap, attack surface overview, and prioritised findings.
 */
export async function generateMarkdownReport(job: ScanJob): Promise<string> {
	const findings = activeFindings(job);
	const counts = severityCounts(findings);
	const date = new Date().toISOString().slice(0, 10);
	const duration =
		job.completedAt && job.startedAt
			? formatDuration(job.completedAt.getTime() - job.startedAt.getTime())
			: "ongoing";

	const lines: string[] = [
		`# Sentinel Security Assessment Report`,
		``,
		`> Generated by setra.sh Sentinel intelligence engine`,
		``,
		`| Field | Value |`,
		`|-------|-------|`,
		`| **Job ID** | \`${job.id}\` |`,
		`| **Target** | \`${job.target}\` |`,
		`| **Status** | ${capitalise(job.status)} |`,
		`| **Date** | ${date} |`,
		`| **Duration** | ${duration} |`,
		`| **Methodology** | ${job.surface ? "Network + Web" : "Static Analysis"} |`,
		``,
		`---`,
		``,
		`## Executive Summary`,
		``,
		`This report documents the findings of an automated security assessment conducted`,
		`by setra's Sentinel intelligence engine against \`${job.target}\`.`,
		``,
		`The assessment identified **${findings.length}** actionable security issues.`,
		counts.critical > 0
			? `**${counts.critical} critical-severity finding(s) require immediate attention** — these represent direct paths to compromise.`
			: `No critical-severity findings were identified during this assessment.`,
		``,
		`### Risk Distribution Heatmap`,
		``,
		`\`\`\``,
		buildHeatmap(counts),
		`\`\`\``,
		``,
		`| Severity | Count | Risk Level |`,
		`|----------|-------|------------|`,
		`| 🔴 Critical | ${counts.critical} | Immediate remediation required |`,
		`| 🟠 High     | ${counts.high}     | Address within 7 days          |`,
		`| 🟡 Medium   | ${counts.medium}   | Address within 30 days         |`,
		`| 🔵 Low      | ${counts.low}      | Address in next sprint         |`,
		`| ⚪ Info      | ${counts.info}     | Informational — review at will |`,
		``,
	];

	// Attack surface overview
	if (job.surface) {
		lines.push(
			`## Attack Surface Overview`,
			``,
			`| Attribute | Value |`,
			`|-----------|-------|`,
			`| **Hostname** | ${job.surface.hostname ?? "—"} |`,
			`| **IP Address** | ${job.surface.ipAddress ?? "—"} |`,
			`| **Open Ports** | ${job.surface.openPorts.filter((p) => p.state === "open").length} |`,
			`| **Services** | ${job.surface.services.length} |`,
			`| **Web Endpoints** | ${job.surface.webEndpoints.length} |`,
			`| **Technologies** | ${job.surface.technologies.join(", ") || "—"} |`,
			``,
		);

		if (job.surface.openPorts.length > 0) {
			lines.push(
				`### Open Ports`,
				``,
				`| Port | Protocol | Service | Version |`,
				`|------|----------|---------|---------|`,
				...job.surface.openPorts
					.filter((p) => p.state === "open")
					.map(
						(p) =>
							`| ${p.port} | ${p.protocol} | ${p.service ?? "—"} | ${p.version ?? "—"} |`,
					),
				``,
			);
		}
	}

	// Findings by severity
	lines.push(`## Findings`, ``);

	for (const sev of SEVERITY_ORDER) {
		const group = findings.filter((f) => f.severity === sev);
		if (!group.length) continue;

		const icon = {
			critical: "🔴",
			high: "🟠",
			medium: "🟡",
			low: "🔵",
			info: "⚪",
		}[sev];
		lines.push(`### ${icon} ${capitalise(sev)} Severity (${group.length})`, ``);

		for (const f of group) {
			lines.push(
				`#### ${f.title}`,
				``,
				`| Field | Value |`,
				`|-------|-------|`,
				`| **Tool** | \`${f.toolUsed}\` |`,
				`| **Target** | \`${f.target}\` |`,
				`| **Discovered** | ${f.discoveredAt.toISOString().slice(0, 19).replace("T", " ")} |`,
				...(f.cvss ? [`| **CVSS Score** | ${f.cvss.baseScore}/10 |`] : []),
				...(f.cveIds.length ? [`| **CVEs** | ${f.cveIds.join(", ")} |`] : []),
				...(f.mitreAttackIds.length
					? [`| **MITRE ATT&CK** | ${f.mitreAttackIds.join(", ")} |`]
					: []),
				``,
				`**Description**`,
				``,
				f.description,
				``,
				`**Evidence**`,
				``,
				"```",
				f.evidence.slice(0, 600),
				"```",
				``,
				`**Remediation**`,
				``,
				f.remediation,
			);

			if (f.references.length) {
				lines.push(``, `**References**`, ``);
				for (const ref of f.references) lines.push(`- ${ref}`);
			}

			lines.push(``, `---`, ``);
		}
	}

	// Remediation priority matrix
	lines.push(
		`## Remediation Priority Matrix`,
		``,
		`| Priority | Finding | Effort | Impact |`,
		`|----------|---------|--------|--------|`,
		...findings
			.filter((f) => ["critical", "high"].includes(f.severity))
			.slice(0, 10)
			.map((f, i) => `| ${i + 1} | ${f.title} | Medium | High |`),
		``,
	);

	// Appendix
	lines.push(
		`## Appendix: Scan Timeline`,
		``,
		`| Timestamp | Phase | Action |`,
		`|-----------|-------|--------|`,
		...job.agentLog
			.slice(0, 30)
			.map(
				(e) =>
					`| ${e.ts.toISOString().slice(11, 19)} | ${e.phase} | ${e.action}: ${e.detail.slice(0, 60)} |`,
			),
		``,
		`*Full log contains ${job.agentLog.length} entries.*`,
		``,
	);

	return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// SARIF 2.1.0 export
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Serialises findings as SARIF 2.1.0 — compatible with GitHub Code Scanning,
 * VS Code SARIF Viewer, Azure DevOps, and any OASIS-compliant tool.
 */
export async function generateSarif(job: ScanJob): Promise<string> {
	const findings = activeFindings(job);
	const rules = new Map<string, object>();

	const results = findings.map((f) => {
		const ruleId = `sentinel/${f.toolUsed}/${slugify(f.title)}`;
		if (!rules.has(ruleId)) {
			rules.set(ruleId, {
				id: ruleId,
				name: f.title,
				shortDescription: { text: f.description.slice(0, 256) },
				fullDescription: { text: f.description },
				helpUri: f.references[0] ?? "https://setra.sh/sentinel",
				properties: {
					tags: ["security", f.severity, ...f.mitreAttackIds],
				},
			});
		}

		return {
			ruleId,
			level: sarifLevel(f.severity),
			message: {
				text: `${f.description}\n\n**Remediation:** ${f.remediation}`,
			},
			locations: [
				{
					physicalLocation: {
						artifactLocation: { uri: f.target, uriBaseId: "%SRCROOT%" },
					},
					logicalLocations: [{ fullyQualifiedName: f.target }],
				},
			],
			fingerprints: {
				"sentinel/v1": dedupHash(f),
			},
			properties: {
				severity: f.severity,
				cvssScore: f.cvss?.baseScore,
				cveIds: f.cveIds,
				mitreAttackIds: f.mitreAttackIds,
				evidence: f.evidence.slice(0, 200),
				discoveredAt: f.discoveredAt.toISOString(),
			},
		};
	});

	const sarif = {
		$schema:
			"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
		version: "2.1.0",
		runs: [
			{
				tool: {
					driver: {
						name: "Sentinel",
						version: "1.0.0",
						semanticVersion: "1.0.0",
						informationUri: "https://setra.sh/sentinel",
						rules: [...rules.values()],
					},
				},
				originalUriBaseIds: {
					"%SRCROOT%": {
						uri: job.target.startsWith("/")
							? `file://${job.target}/`
							: `${job.target}/`,
					},
				},
				results,
				properties: {
					jobId: job.id,
					target: job.target,
					scanStatus: job.status,
					startedAt: job.startedAt?.toISOString(),
					completedAt: job.completedAt?.toISOString(),
				},
			},
		],
	};

	return JSON.stringify(sarif, null, 2);
}

// ─────────────────────────────────────────────────────────────────────────────
// JSON export
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Full structured JSON export — suitable for machine processing, API responses,
 * and integrations that consume Sentinel output programmatically.
 */
export async function generateJson(job: ScanJob): Promise<string> {
	const counts = severityCounts(activeFindings(job));

	const output = {
		jobId: job.id,
		target: job.target,
		status: job.status,
		phase: job.phase,
		startedAt: job.startedAt?.toISOString(),
		completedAt: job.completedAt?.toISOString(),
		summary: {
			totalFindings: job.findings.length,
			activeFindings: activeFindings(job).length,
			falsePositives: job.findings.filter((f) => f.falsePositive).length,
			bySeverity: counts,
		},
		surface: job.surface,
		findings: activeFindings(job).map((f) => ({
			id: f.id,
			title: f.title,
			description: f.description,
			severity: f.severity,
			cvss: f.cvss,
			cveIds: f.cveIds,
			mitreAttackIds: f.mitreAttackIds,
			remediation: f.remediation,
			references: f.references,
			discoveredAt: f.discoveredAt.toISOString(),
			target: f.target,
			toolUsed: f.toolUsed,
			evidence: f.evidence,
		})),
		agentLog: job.agentLog.map((e) => ({
			...e,
			ts: e.ts.toISOString(),
		})),
		generatedAt: new Date().toISOString(),
		generator: "Sentinel 1.0.0 (setra.sh)",
	};

	return JSON.stringify(output, null, 2);
}

// ─────────────────────────────────────────────────────────────────────────────
// CSV export
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Exports findings as CSV for spreadsheet import or bulk ticket creation
 * in Jira, GitHub Issues, Linear, and similar trackers.
 */
export async function generateCsv(job: ScanJob): Promise<string> {
	const findings = activeFindings(job);

	const headers = [
		"ID",
		"Title",
		"Severity",
		"CVSS Score",
		"CVEs",
		"MITRE ATT&CK",
		"Target",
		"Tool Used",
		"Description",
		"Remediation",
		"Evidence",
		"Discovered At",
		"References",
	];

	const rows = findings.map((f) => [
		f.id,
		f.title,
		f.severity,
		f.cvss?.baseScore?.toString() ?? "",
		f.cveIds.join("; "),
		f.mitreAttackIds.join("; "),
		f.target,
		f.toolUsed,
		f.description,
		f.remediation,
		f.evidence.slice(0, 300).replace(/\n/g, " "),
		f.discoveredAt.toISOString(),
		f.references.join("; "),
	]);

	const lines = [headers, ...rows].map((row) =>
		row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","),
	);

	return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

function buildHeatmap(counts: Record<SeverityLevel, number>): string {
	const maxBar = 30;
	const total = Object.values(counts).reduce((a, b) => a + b, 0) || 1;
	const lines: string[] = [];

	for (const sev of SEVERITY_ORDER) {
		const n = counts[sev];
		const bar = "█".repeat(Math.round((n / total) * maxBar));
		const label = capitalise(sev).padEnd(9);
		lines.push(`${label} ${bar.padEnd(maxBar)} ${n}`);
	}

	return lines.join("\n");
}

function sarifLevel(severity: SeverityLevel): string {
	switch (severity) {
		case "critical":
		case "high":
			return "error";
		case "medium":
			return "warning";
		default:
			return "note";
	}
}

function slugify(s: string): string {
	return s
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.slice(0, 50);
}

function dedupHash(f: Finding): string {
	// Deterministic fingerprint without importing crypto for this helper
	const key = `${f.target}|${f.title}|${f.toolUsed}`;
	let h = 0;
	for (let i = 0; i < key.length; i++) {
		h = (Math.imul(31, h) + key.charCodeAt(i)) >>> 0;
	}
	return h.toString(16).padStart(8, "0");
}

function formatDuration(ms: number): string {
	const s = Math.floor(ms / 1000);
	if (s < 60) return `${s}s`;
	const m = Math.floor(s / 60);
	if (m < 60) return `${m}m ${s % 60}s`;
	return `${Math.floor(m / 60)}h ${m % 60}m`;
}
