import { describe, expect, it } from "vitest";
import {
	renderRunBundleMarkdown,
	renderRunToolCallsTsv,
} from "../lib/run-bundle-markdown.js";
import type { RunBundle } from "../lib/run-bundle.js";

function makeBundle(overrides: Partial<RunBundle> = {}): RunBundle {
	return {
		run: {
			id: "run-1",
			agentSlug: "engineer",
			displayName: "Engineer",
			companyId: "co-1",
			status: "success",
			startedAt: "t0",
			endedAt: "t1",
			firstChunkAt: "t0",
			exitCode: 0,
			systemPrompt: "You are an engineer.",
			issueId: "issue-1",
		},
		systemPrompt: "You are an engineer.",
		chunks: [],
		toolCalls: [
			{
				sequence: 1,
				toolName: "edit",
				input: JSON.stringify({ path: "src/x.ts" }),
				output: "ok",
				startedAt: "t0",
				completedAt: "t1",
			},
		],
		filesTouched: [{ path: "src/x.ts", tool: "edit", firstSeenAt: "t0" }],
		artifacts: [
			{ id: "a1", name: "commit:abc", mimeType: "json", createdAt: "t1" },
		],
		stats: { chunkCount: 2, toolCallCount: 1, fileCount: 1, artifactCount: 1 },
		...overrides,
	} as RunBundle;
}

describe("renderRunBundleMarkdown", () => {
	it("includes the run header, system prompt, tool calls, and files", () => {
		const md = renderRunBundleMarkdown(makeBundle());
		expect(md).toContain("# Setra run evidence: run-1");
		expect(md).toContain("`engineer`");
		expect(md).toContain("You are an engineer.");
		expect(md).toContain("Tool calls (showing 1 of 1)");
		expect(md).toContain("src/x.ts");
		expect(md).toContain("commit:abc");
		expect(md).toContain("Generated by Setra. Do not edit by hand.");
	});

	it("truncates very long tool inputs", () => {
		const md = renderRunBundleMarkdown(
			makeBundle({
				toolCalls: [
					{
						sequence: 1,
						toolName: "bash",
						input: "x".repeat(5000),
						output: null,
						startedAt: "t0",
						completedAt: null,
					},
				],
			}),
		);
		expect(md).toContain("[truncated");
	});
});

describe("renderRunToolCallsTsv", () => {
	it("emits a header row plus one row per tool call", () => {
		const tsv = renderRunToolCallsTsv(makeBundle());
		const rows = tsv.split("\n");
		expect(rows[0]).toBe(
			"sequence\ttool\tstartedAt\tcompletedAt\tinputChars\toutputChars",
		);
		expect(rows).toHaveLength(2);
		expect(rows[1]).toContain("edit");
	});
});
