/**
 * Render a RunBundle into the markdown body used as the description of a
 * Setra-managed pull request. Mirrors the autoresearch PR-from-run pattern:
 * the PR body itself becomes the durable evidence record.
 *
 * The output is intentionally compact (capped per-section) so it stays within
 * GitHub's 262 KB pull-request body limit even for long-running agents.
 */

import type { RunBundle } from "./run-bundle.js";

const MAX_TOOL_CALLS = 50;
const MAX_FILES = 100;
const MAX_PROMPT_CHARS = 4000;
const MAX_TOOL_INPUT_CHARS = 600;
const MAX_TOOL_OUTPUT_CHARS = 600;

function truncate(value: string | null | undefined, max: number): string {
	if (!value) return "";
	if (value.length <= max) return value;
	return `${value.slice(0, max)}\n... [truncated ${value.length - max} chars]`;
}

export function renderRunBundleMarkdown(bundle: RunBundle): string {
	const lines: string[] = [];
	const { run, stats } = bundle;

	lines.push(`# Setra run evidence: ${run.id}`);
	lines.push("");
	lines.push("| Field | Value |");
	lines.push("| --- | --- |");
	lines.push(`| Agent | \`${run.agentSlug}\` |`);
	lines.push(`| Display name | ${run.displayName ?? "n/a"} |`);
	lines.push(`| Status | ${run.status ?? "unknown"} |`);
	lines.push(`| Exit code | ${run.exitCode ?? "n/a"} |`);
	lines.push(`| Started | ${run.startedAt ?? "n/a"} |`);
	lines.push(`| Ended | ${run.endedAt ?? "n/a"} |`);
	lines.push(`| Issue | ${run.issueId ?? "n/a"} |`);
	lines.push("");
	lines.push("## Counts");
	lines.push("");
	lines.push(`- Chunks: ${stats.chunkCount}`);
	lines.push(`- Tool calls: ${stats.toolCallCount}`);
	lines.push(`- Files touched: ${stats.fileCount}`);
	lines.push(`- Artifacts: ${stats.artifactCount}`);
	lines.push("");

	if (bundle.systemPrompt) {
		lines.push("## System prompt");
		lines.push("");
		lines.push("```text");
		lines.push(truncate(bundle.systemPrompt, MAX_PROMPT_CHARS));
		lines.push("```");
		lines.push("");
	}

	if (bundle.toolCalls.length > 0) {
		lines.push(
			`## Tool calls (showing ${Math.min(bundle.toolCalls.length, MAX_TOOL_CALLS)} of ${bundle.toolCalls.length})`,
		);
		lines.push("");
		for (const call of bundle.toolCalls.slice(0, MAX_TOOL_CALLS)) {
			lines.push(`### ${call.sequence}. ${call.toolName ?? "unknown"}`);
			lines.push(`- started: ${call.startedAt}`);
			if (call.completedAt) lines.push(`- completed: ${call.completedAt}`);
			lines.push("");
			lines.push("Input:");
			lines.push("```");
			lines.push(truncate(call.input, MAX_TOOL_INPUT_CHARS));
			lines.push("```");
			if (call.output) {
				lines.push("Output:");
				lines.push("```");
				lines.push(truncate(call.output, MAX_TOOL_OUTPUT_CHARS));
				lines.push("```");
			}
			lines.push("");
		}
	}

	if (bundle.filesTouched.length > 0) {
		lines.push(
			`## Files touched (showing ${Math.min(bundle.filesTouched.length, MAX_FILES)} of ${bundle.filesTouched.length})`,
		);
		lines.push("");
		for (const file of bundle.filesTouched.slice(0, MAX_FILES)) {
			lines.push(
				`- \`${file.path}\` (via ${file.tool}, first seen ${file.firstSeenAt})`,
			);
		}
		lines.push("");
	}

	if (bundle.artifacts.length > 0) {
		lines.push("## Artifacts");
		lines.push("");
		for (const art of bundle.artifacts) {
			lines.push(`- ${art.name} (${art.mimeType ?? "?"})`);
		}
		lines.push("");
	}

	lines.push("---");
	lines.push("Generated by Setra. Do not edit by hand.");
	return lines.join("\n");
}

/**
 * Render the run's tool-call ledger as a TSV blob suitable for attaching to
 * a PR review or downloading as evidence.
 */
export function renderRunToolCallsTsv(bundle: RunBundle): string {
	const header =
		"sequence\ttool\tstartedAt\tcompletedAt\tinputChars\toutputChars";
	const rows = bundle.toolCalls.map(
		(c) =>
			`${c.sequence}\t${c.toolName ?? ""}\t${c.startedAt}\t${c.completedAt ?? ""}\t${c.input.length}\t${(c.output ?? "").length}`,
	);
	return [header, ...rows].join("\n");
}
