/**
 * ClaudeAdapter — wraps the Claude Code CLI (`claude` binary).
 *
 * Key design decisions (see SETRA_BLUEPRINT.txt §1.1):
 *   - Every run is a fresh `claude -p '<task>'` invocation. No --resume.
 *     This keeps the prefix identical → triggers Anthropic prompt cache.
 *   - Output format: stream-json for reliable cost/token parsing.
 *   - System prompt is appended (never replaced) to preserve Claude's
 *     built-in coding agent behaviours.
 *   - The MCP config is per-plot, generated by packages/mcp/config-gen.ts.
 *
 * Claude Code CLI reference flags used here:
 *   -p / --print              Non-interactive mode; exits when done
 *   --model <id>              Model selection
 *   --output-format <fmt>     "stream-json" | "json" | "text"
 *   --max-turns <n>           Cap agent turns (default: 40)
 *   --mcp-config <path>       Per-plot MCP server config
 *   --append-system-prompt    Add to the default system prompt
 *   --allowedTools <list>     Comma-separated tool allow-list
 *   --no-conversation         Do not persist conversation history to ~/.claude
 */

import { execFileSync } from "child_process";
import type { AgentAdapter } from "../adapter.js";
import type { Plot, Run, SpawnOptions, TokenUsage } from "../types.js";

// ─── Rate-limit detection patterns ───────────────────────────────────────────
//
// These are shared with fallback-chain.ts via re-export so both the adapter
// and the chain monitor use the same patterns.

export const CLAUDE_RATE_LIMIT_PATTERNS: readonly RegExp[] = [
	/rate[\s_-]?limit/i,
	/\b429\b/,
	/overloaded/i,
	/quota\s+exceeded/i,
	/try\s+again\s+later/i,
	/too\s+many\s+requests/i,
	/capacity/i,
	/"error_code"\s*:\s*"overloaded_error"/,
	/"type"\s*:\s*"error".*"message"\s*:\s*".*overload/i,
] as const;

// ─── Completion detection patterns ───────────────────────────────────────────

const CLAUDE_COMPLETION_PATTERNS: readonly RegExp[] = [
	// stream-json final result event
	/"type"\s*:\s*"result"\s*,\s*"subtype"\s*:\s*"(?:success|error)"/,
	// Text-mode summary line that appears at the very end
	/Total\s+cost:\s+\$[\d.]+/,
	// Claude Code's "task complete" indicator
	/✓\s+(?:Task\s+)?(?:complete|done|finished)/i,
] as const;

// ─── Token / cost parsing patterns ───────────────────────────────────────────

/**
 * stream-json final result line shape:
 * {"type":"result","subtype":"success","total_cost_usd":0.1234,
 *  "input_tokens":1000,"output_tokens":234,
 *  "cache_read_input_tokens":800,"cache_creation_input_tokens":0, ...}
 */
const STREAM_JSON_RESULT =
	/"type"\s*:\s*"result"[^}]+"total_cost_usd"\s*:\s*([\d.]+)/;
const STREAM_JSON_INPUT_TOKENS = /"input_tokens"\s*:\s*(\d+)/;
const STREAM_JSON_OUTPUT_TOKENS = /"output_tokens"\s*:\s*(\d+)/;
const STREAM_JSON_CACHE_READ = /"cache_read_input_tokens"\s*:\s*(\d+)/;
const STREAM_JSON_CACHE_WRITE = /"cache_creation_input_tokens"\s*:\s*(\d+)/;

/**
 * Text-mode patterns — the real Claude Code CLI output format (from fixtures):
 *
 *   Total cost:            $0.0523
 *   Token usage:
 *     Input:               12,345
 *     Output:              1,234
 *     Cache read:          10,891
 *     Cache write:         2,345
 *
 * Uses the same regexes as cost-tracker.ts for consistency.
 * ANSI stripping happens in parseTokenUsage() before matching.
 */
// eslint-disable-next-line no-control-regex
const STRIP_ANSI_RE = /\x1b\[[0-9;]*[mGKHFABCDJsu]/g;
const TEXT_COST_LINE = /Total cost:\s+\$?([\d.]+)/gi;
const TEXT_INPUT_TOKENS = /Input:\s+([\d,]+)/i;
const TEXT_OUTPUT_TOKENS = /Output:\s+([\d,]+)/i;
const TEXT_CACHE_READ = /Cache read:\s+([\d,]+)/i;
const TEXT_CACHE_WRITE = /Cache write:\s+([\d,]+)/i;

// ─── ClaudeAdapter ────────────────────────────────────────────────────────────

export class ClaudeAdapter implements AgentAdapter {
	readonly name = "claude" as const;
	readonly displayName = "Claude Code (Anthropic)";
	readonly supportsModels = [
		"auto",
		"claude-opus-4-5",
		"claude-sonnet-4-5",
		"claude-haiku-4-5",
	] as const;

	/**
	 * Default model for non-"auto" runs.
	 * In Team Mode: orchestrator gets opus, workers get sonnet (see §1.5 MODEL ROLES).
	 * For solo runs: sonnet — best cost/quality balance.
	 */
	readonly defaultModel = "claude-sonnet-4-5";

	// ── isAvailable ─────────────────────────────────────────────────────────────

	async isAvailable(): Promise<boolean> {
		try {
			execFileSync("which", ["claude"], { stdio: "pipe" });
			return true;
		} catch {
			return false;
		}
	}

	// ── buildCommand ─────────────────────────────────────────────────────────────

	buildCommand(plot: Plot, run: Run, mcpConfigPath: string): SpawnOptions {
		const model = this.resolveModel(run.model);

		const args: string[] = [
			// Non-interactive print mode — exits when the task is done.
			"--print",

			// JSON stream output: makes token/cost parsing deterministic.
			// Every agent turn emits structured events; the final line is the result.
			"--output-format",
			"stream-json",

			"--model",
			model,

			// Cap turns to prevent runaway costs. Blueprint default: 40.
			"--max-turns",
			String(run.maxTurns ?? 40),

			// Do not write conversation history to ~/.claude/projects/.
			// We store everything in the setra trace store instead.
			"--no-conversation",
		];

		// MCP config (per-plot, generated by packages/mcp/config-gen.ts)
		args.push(...this.buildMcpArgs(mcpConfigPath));

		// Optional budget enforcement via cost limit flag.
		// Claude Code CLI supports --cost-limit (budget in USD).
		const budget = run.budgetUsd ?? plot.budgetUsd;
		if (budget != null) {
			args.push("--cost-limit", String(budget));
		}

		// Append setra's orchestration instructions to the system prompt.
		// We NEVER replace the full system prompt — Claude's built-in tool
		// definitions and safety context must remain intact.
		if (run.systemPromptAppend) {
			args.push(...this.buildSystemPromptArgs(run.systemPromptAppend));
		}

		// Task description is always the final positional argument.
		args.push(run.task);

		return {
			cmd: "claude",
			args,
			env: {
				// Inject setra context so MCP tools and any hook scripts can read them.
				SETRA_PLOT_ID: plot.id,
				SETRA_RUN_ID: run.id,
				SETRA_AGENT: this.name,
				SETRA_MODEL: model,
			},
			cwd: plot.worktreePath,
		};
	}

	// ── buildSystemPromptArgs ────────────────────────────────────────────────────

	buildSystemPromptArgs(systemPrompt: string): string[] {
		return ["--append-system-prompt", systemPrompt];
	}

	// ── buildMcpArgs ─────────────────────────────────────────────────────────────

	buildMcpArgs(mcpConfigPath: string): string[] {
		return ["--mcp-config", mcpConfigPath];
	}

	// ── parseTokenUsage ──────────────────────────────────────────────────────────

	parseTokenUsage(output: string): TokenUsage | null {
		const clean = output.replace(STRIP_ANSI_RE, "");
		const parseNum = (s: string | undefined) =>
			Number.parseInt((s ?? "0").replace(/,/g, ""), 10);

		// Primary: stream-json result event (most reliable, used with --output-format stream-json)
		if (STREAM_JSON_RESULT.test(clean)) {
			const inputMatch = STREAM_JSON_INPUT_TOKENS.exec(clean);
			const outputMatch = STREAM_JSON_OUTPUT_TOKENS.exec(clean);
			if (inputMatch && outputMatch) {
				return {
					promptTokens: parseNum(inputMatch[1]),
					completionTokens: parseNum(outputMatch[1]),
					cacheReadTokens: parseNum(STREAM_JSON_CACHE_READ.exec(clean)?.[1]),
					cacheWriteTokens: parseNum(STREAM_JSON_CACHE_WRITE.exec(clean)?.[1]),
				};
			}
		}

		// Fallback: text-mode "Token usage: / Input: 12,345 / Output: 1,234 / Cache read: ..."
		// This is the real Claude Code CLI format (see tests/fixtures/claude-pty-output.txt)
		const allCostMatches = [...clean.matchAll(TEXT_COST_LINE)];
		if (allCostMatches.length === 0) return null;

		// Find the token block after the last cost occurrence
		const lastCostMatch = allCostMatches[allCostMatches.length - 1];
		if (!lastCostMatch) return null;
		const lastCostIndex = clean.lastIndexOf(lastCostMatch[0]);
		const afterCost = clean.slice(lastCostIndex);

		const inputMatch = TEXT_INPUT_TOKENS.exec(afterCost);
		const outputMatch = TEXT_OUTPUT_TOKENS.exec(afterCost);
		if (!inputMatch || !outputMatch) return null;

		return {
			promptTokens: parseNum(inputMatch[1]),
			completionTokens: parseNum(outputMatch[1]),
			cacheReadTokens: parseNum(TEXT_CACHE_READ.exec(afterCost)?.[1]),
			cacheWriteTokens: parseNum(TEXT_CACHE_WRITE.exec(afterCost)?.[1]),
		};
	}

	// ── parseCostUSD ─────────────────────────────────────────────────────────────

	parseCostUSD(output: string): number | null {
		const clean = output.replace(STRIP_ANSI_RE, "");

		// Primary: stream-json result event
		const jsonMatch = STREAM_JSON_RESULT.exec(clean);
		if (jsonMatch) {
			const cost = Number.parseFloat(jsonMatch[1] ?? "NaN");
			return isNaN(cost) ? null : cost;
		}

		// Fallback: real Claude Code text format "Total cost: $0.0523"
		// Find ALL occurrences and return the last one (most recent run in PTY session)
		const allMatches = [...clean.matchAll(TEXT_COST_LINE)];
		if (allMatches.length === 0) return null;
		const last = allMatches[allMatches.length - 1];
		if (!last) return null;
		const cost = Number.parseFloat((last[1] ?? "").replace(/^\$/, ""));
		return isNaN(cost) ? null : cost;
	}

	// ── detectRateLimit ──────────────────────────────────────────────────────────

	detectRateLimit(output: string): boolean {
		return CLAUDE_RATE_LIMIT_PATTERNS.some((pattern) => pattern.test(output));
	}

	// ── detectCompletion ─────────────────────────────────────────────────────────

	detectCompletion(output: string): boolean {
		const clean = output.replace(STRIP_ANSI_RE, "");
		return CLAUDE_COMPLETION_PATTERNS.some((pattern) => pattern.test(clean));
	}

	// ── Private helpers ──────────────────────────────────────────────────────────

	private resolveModel(modelId: string): string {
		if (modelId === "auto" || !this.supportsModels.includes(modelId as never)) {
			return this.defaultModel;
		}
		return modelId;
	}
}

// ─── Singleton export ─────────────────────────────────────────────────────────

export const claudeAdapter = new ClaudeAdapter();
