import type { SlashCommandEntry } from "./types.js";

const BUILTIN_COMMANDS: SlashCommandEntry[] = [
	{
		name: "new",
		aliases: ["clear"],
		description: "Start a fresh agent session",
		argumentHint: "",
		kind: "builtin",
		source: "builtin",
		action: { type: "new_session" },
	},
	{
		name: "stop",
		aliases: [],
		description: "Stop the running agent",
		argumentHint: "",
		kind: "builtin",
		source: "builtin",
		action: { type: "stop_run" },
	},
	{
		name: "model",
		aliases: [],
		description: "Switch active model",
		argumentHint: "[model-id]",
		kind: "builtin",
		source: "builtin",
		action: { type: "set_model", passArguments: true },
	},
	{
		name: "mcp",
		aliases: [],
		description: "Show MCP server overview",
		argumentHint: "",
		kind: "builtin",
		source: "builtin",
		action: { type: "show_mcp" },
	},
	{
		name: "skills",
		aliases: [],
		description: "Browse and create skills",
		argumentHint: "",
		kind: "builtin",
		source: "builtin",
		action: { type: "show_skills" },
	},
	{
		name: "instances",
		aliases: ["inst"],
		description: "List running setra instances",
		argumentHint: "",
		kind: "builtin",
		source: "builtin",
		action: { type: "show_instances" },
	},
	{
		name: "allow-all",
		aliases: ["allow"],
		description: "Grant tool use without prompting",
		argumentHint: "",
		kind: "builtin",
		source: "builtin",
		action: { type: "allow_all" },
	},
	{
		name: "deny-all",
		aliases: [],
		description: "Revoke all pending tool grants",
		argumentHint: "",
		kind: "builtin",
		source: "builtin",
		action: { type: "deny_all" },
	},
	{
		name: "compact",
		aliases: [],
		description: "Summarise history to reduce tokens",
		argumentHint: "",
		kind: "builtin",
		source: "builtin",
		action: { type: "compact" },
	},
	{
		name: "cost",
		aliases: ["spend"],
		description: "Show spend for this session",
		argumentHint: "",
		kind: "builtin",
		source: "builtin",
		action: { type: "show_cost" },
	},
	{
		name: "cron",
		aliases: ["schedule"],
		description: "Schedule a recurring agent run",
		argumentHint: '"<cron-expr> <task>"',
		kind: "builtin",
		source: "builtin",
		template: "Schedule recurring task. Cron: $ARGUMENTS",
	},
	{
		name: "review",
		aliases: [],
		description: "Review code for bugs/regressions",
		argumentHint: "[scope]",
		kind: "builtin",
		source: "builtin",
		template: [
			"Please review this work for correctness and risk.",
			"If scope/context is provided, prioritize it: $ARGUMENTS",
			"Return findings ordered by severity with file references.",
		].join("\n"),
	},
	{
		name: "plan",
		aliases: [],
		description: "Draft implementation plan",
		argumentHint: "[goal]",
		kind: "builtin",
		source: "builtin",
		template: [
			"Create a concise implementation plan.",
			"If a goal is provided, target this: $ARGUMENTS",
			"Include phases, risks, and verification steps.",
		].join("\n"),
	},
	{
		name: "test",
		aliases: [],
		description: "Design tests for target",
		argumentHint: "[target]",
		kind: "builtin",
		source: "builtin",
		template: [
			"Design and run tests for the requested change.",
			"Primary target/context (optional): $ARGUMENTS",
			"Focus on behavioral regressions and edge cases.",
		].join("\n"),
	},
	{
		name: "refactor",
		aliases: [],
		description: "Propose refactor with safeguards",
		argumentHint: "[scope]",
		kind: "builtin",
		source: "builtin",
		template: [
			"Refactor request",
			"Scope/context: $ARGUMENTS",
			"Propose staged changes with safeguards and verification.",
		].join("\n"),
	},
	{
		name: "approve",
		aliases: [],
		description: "Approve a pending agent action",
		argumentHint: "[action-id]",
		kind: "builtin",
		source: "builtin",
		template: "Approve the pending agent action: $ARGUMENTS",
	},
	{
		name: "deny",
		aliases: [],
		description: "Deny a specific pending action",
		argumentHint: "[action-id]",
		kind: "builtin",
		source: "builtin",
		template: "Deny the pending agent action: $ARGUMENTS",
	},
	{
		name: "memory",
		aliases: ["remember"],
		description: "Store a fact in agent memory",
		argumentHint: '"<key> <value>"',
		kind: "builtin",
		source: "builtin",
		template:
			"Remember the following fact in your long-term memory: $ARGUMENTS",
	},
	{
		name: "ssh",
		aliases: ["ground"],
		description: "Connect to a remote ground",
		argumentHint: "[host]",
		kind: "builtin",
		source: "builtin",
		template: "Connect to the remote ground at: $ARGUMENTS",
	},
	{
		name: "help",
		aliases: ["?"],
		description: "Show all commands and shortcuts",
		argumentHint: "",
		kind: "builtin",
		source: "builtin",
		template: "List all /commands with descriptions and keyboard shortcuts.",
	},
];

export function getBuiltinCommands(): SlashCommandEntry[] {
	return BUILTIN_COMMANDS.map((cmd) => {
		const entry: SlashCommandEntry = {
			name: cmd.name,
			aliases: [...cmd.aliases],
			description: cmd.description,
			argumentHint: cmd.argumentHint,
			kind: cmd.kind,
			source: cmd.source,
		};
		if (cmd.action) entry.action = { ...cmd.action };
		if (cmd.template) entry.template = cmd.template;
		if (cmd.filePath) entry.filePath = cmd.filePath;
		return entry;
	});
}
